### ISSUE TITLE
Problem starting a Nuxt 3 project with oxc-parser

### ISSUE THREAD

**Issue by WaiRung** [oxc-project/oxc#11459]
From [Nuxt Issue](https://github.com/nuxt/nuxt/issues/31954) I have come across with Window issue. I tried to start a brand new Nuxt 3 project with the error and the only solution I found is the above discussion, here are my environment details.
**Environment**

Nuxt Version: ^3.17.2
Node.js Version: 20, 22
npm verions: 11.4.1
Server Architecture: win32-x64
Package Manager: npm

**Describe the bug**

![Image](https://github.com/user-attachments/assets/1fe0fa71-5a8c-4da8-a5cc-61ea2b70e50d)

**Comment by Boshen** [comment]
What is your `npm -v`? It's fixed in later versions of npm according to https://github.com/npm/cli/pull/8184

You may need to 

```
rm -rf node_modules package-lock.json

npm cache clean --force

npm install
```

according to https://github.com/npm/cli/issues/4828

**Comment by WaiRung** [comment]
@Boshen I have tried the above steps and the error still persists, and I even created a brand new Nuxt project with Nuxt version 3.17.4. For npm, the version is 11.4.1

**Comment by Boshen** [comment]
Does it work with `pnpm`? I'd like to isolate the bug between package manager and your os.

What happens if you manually add `@oxc-parser/binding-win32-x64-msvc` to your package.json?

**Comment by WaiRung** [comment]
@Boshen With some dependencies are out of order, it works with pnpm magically.
For manually added @oxc-parser/binding-win32-x64-msvc, the error changes

![Image](https://github.com/user-attachments/assets/0e4eaff1-c4e9-46a7-8197-716e25717e82)
I've tried adding @rollup/rollup-win32-x64-msvc. manually because I had @rollup/rollup-win32-x64-msvc problem about a month ago too, still this error.

My odds are with npm issues, should I migrate to pnpm?

**Comment by WaiRung** [comment]
@Boshen I am very appreciated for your assistance.
Have you isolated the cause? Is it because oxc-parser, npm or the os?
So I could decide the fate of my project.

**Comment by Boshen** [comment]
Use `pnpm`.

**Comment by kroehre** [comment]
@Boshen I'm running into this same issue using `pnpm`. I've tried `npm` and `yarn` and the issue persists. This is in a `node:22-slim` docker container.

**Comment by WaiRung** [comment]
@kroehre I'm running locally in Windows hence "parser.win32-x64-mvcs.node". Is your container Windows OS?

**Comment by kingychiu** [comment]
Same issue, working locally but failed during AWS CodeBuild Deployment (arm env)

```
RUN npm install --platform=linux --architecture=arm64 --libc=glibc
```

**Comment by aube** [comment]
Just install the oxc-parser 
```
pnpm i @oxc-parser/binding-linux-x64-gnu
```

**Comment by sunbromarko** [comment]
We need some strong solution. My CI/CD fails if repo contain .lock file
Our team all have different OS environment, but have never fave problem with diff .lock deps by OS

Delete .lock file isn`t solution at all. Cursed way to have no cache in ci/cd

**Comment by chsami** [comment]
setting my node version to 22 in my github action fixed this

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

**Comment by gregdev** [comment]
Thanks @chsami for the hint. I edited the settings of my Cloudflare Pages app to switch the build system from version 2 to version 3 and now things are deploying again.

**Comment by Boshen** [comment]
This is a npm (< v11.3.0) bug, things you can try:

* use latest npm
* use pnpm
* `rm -rf node_modules; npm i`
* Install one of these bindings explicitly in your package.json because package manager is not picking up the optional dependency: 

```
"@oxc-parser/binding-win32-x64-msvc"
"@oxc-parser/binding-win32-arm64-msvc"
"@oxc-parser/binding-linux-x64-gnu"
"@oxc-parser/binding-linux-x64-musl"
"@oxc-parser/binding-freebsd-x64"
"@oxc-parser/binding-linux-arm64-gnu"
"@oxc-parser/binding-linux-arm64-musl"
"@oxc-parser/binding-linux-arm-gnueabihf"
"@oxc-parser/binding-linux-arm-musleabihf"
"@oxc-parser/binding-linux-s390x-gnu"
"@oxc-parser/binding-linux-riscv64-gnu"
"@oxc-parser/binding-darwin-x64"
"@oxc-parser/binding-darwin-arm64"
"@oxc-parser/binding-android-arm64"
"@oxc-parser/binding-wasm32-wasi"
```

**Comment by hlassiege** [comment]
I have the exact same issue, with npm or pnpm

npm version 10.9.3
pnpm version 10.18.3
node 22.11.0
nuxt 4.1.3
deployed on coolify


#11 14.51 > nuxt prepare
2025-Oct-14 16:30:44.869486
#11 14.51
2025-Oct-14 16:30:45.781521
#11 15.42 [error] Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
2025-Oct-14 16:30:45.781521
#11 15.42   at node_modules/.pnpm/oxc-parser@0.94.0/node_modules/oxc-parser/src-js/bindings.js:553:11
