### ISSUE TITLE
minifier: does not eliminate unnecessary side-effect free function call

### ISSUE THREAD

**Issue by TheAlexLichter** [oxc-project/oxc#13027]
## Case

When a side-effect free function is called multiple times, the call could be removed. Same applies to *unused* variables assigned to the result of the side-effect free function

[Reproduction](https://playground.oxc.rs/#eNplj0FrwzAMhf+K0amFMLbBLhm7jV43tmsuiqtkBkcKstOulPz32UkdBj3Zepa/994VLNTQcDexjU7YdCK7vbk2bIxSnJRN1Ikanhtu2AqHaNC8rWuvRWnvFPtPWTXx9OCl3+EeKhCor6AT5yNcOOIv1NmnAu84lnuwMtI2XIZWfJmiIodOdIC6Qx9ormBEDaSZiN7L+WtJ/zHF4I50uNUr30eltHuiT1TisKoJkc0XRLpvDiszovaUkgGF58enl9TBpUoY6fhO1qNixidSSWPlSD0tBYmx9fQtk1oacNzcBseucyveypAz3aJUcP5xkcKINvVfkGkdufdlXBw4qvhD6poJJ9JWwvaeG6S0Jcb8B/QerT4=)

## Expected output

```ts
function foo() {
  return !0
}

const a = foo();

console.log(a);
```

or a smaller version like - though above would suffice for now.

```ts

```ts
function foo() {
  return !0
}

console.log(foo());
```

## Actual output

```ts
function foo() {
	return !0;
}
const a = foo();
foo(), foo(), console.log(a);
```

## Info

Originally reported in https://github.com/rolldown/rolldown/issues/5712

**Comment by TheAlexLichter** [comment]
Resolved via #13026

**Comment by sapphi-red** [comment]
The linked repro was not fixed. `foo()` is still included in the output.

I guess
```js
function foo() {
  return !0
}
```
needs to be marked as side effect free, but IIRC Oxc currently only marks functions that is empty as side effect free.

**Comment by sapphi-red** [comment]
Fixed by #13403
