### ISSUE TITLE
formatter: cannot find native binding on Windows when ran from local (project) installation

### ISSUE THREAD

**Issue by thobas-dnvgl** [oxc-project/oxc#15560]
I am running Window 11, Node.js v24.11.0 and npm 11.6.2.

The error message makes me think that you are aware of this issue but I did not manage to find it on GitHub.

I tried the workaround mentioned in the error ("Please try npm i again after removing both package-lock.json and node_modules directory."), but it did not help.

Running `npm i -g oxfmt@latest && oxfmt .` in the same path works though. Yes, both local and global `oxfmt` are 0.13.0.

Anything I can do to help you solved this issue?

```
.\node_modules\.bin\oxfmt .
file:///C:/Users/XXX/ClientApp/node_modules/oxfmt/dist/embedded-DV4TApdj.js:480
        if (loadErrors.length > 0) throw new Error("Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.", { cause: loadErrors.reduce((err, cur) => {
                                         ^

Error: Cannot find native binding. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at file:///C:/Users/XXX/ClientApp/node_modules/oxfmt/dist/embedded-DV4TApdj.js:480:35
    at ModuleJob.run (node:internal/modules/esm/module_job:377:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:691:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5) {
  [cause]: Error: Cannot find module '@oxfmt/win32-x64'
  Require stack:
  - C:\Users\XXX\ClientApp\node_modules\oxfmt\dist\embedded-DV4TApdj.js
      at Module._resolveFilename (node:internal/modules/cjs/loader:1420:15)
      ... 6 lines matching cause stack trace ...
      at require (node:internal/modules/helpers:152:16)
      at requireNative (file:///C:/Users/XXX/ClientApp/node_modules/oxfmt/dist/embedded-DV4TApdj.js:126:20)
      at file:///C:/Users/XXX/ClientApp/node_modules/oxfmt/dist/embedded-DV4TApdj.js:454:17 {
    code: 'MODULE_NOT_FOUND',
    requireStack: [
      'C:\\Users\\XXX\\ClientApp\\node_modules\\oxfmt\\dist\\embedded-DV4TApdj.js'
    ],
    cause: Error: Cannot find module './oxfmt.win32-x64-msvc.node'
    Require stack:
    - C:\Users\XXX\ClientApp\node_modules\oxfmt\dist\embedded-DV4TApdj.js
        at Module._resolveFilename (node:internal/modules/cjs/loader:1420:15)
        at defaultResolveImpl (node:internal/modules/cjs/loader:1058:19)
        at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1063:22)
        at Module._load (node:internal/modules/cjs/loader:1226:37)
        at TracingChannel.traceSync (node:diagnostics_channel:328:14)
        at wrapModuleLoad (node:internal/modules/cjs/loader:244:24)
        at Module.require (node:internal/modules/cjs/loader:1503:12)
        at require (node:internal/modules/helpers:152:16)
        at requireNative (file:///C:/Users/XXX/node_modules/oxfmt/dist/embedded-DV4TApdj.js:121:11)
        at file:///C:/Users/XXX/ClientApp/node_modules/oxfmt/dist/embedded-DV4TApdj.js:454:17 {
      code: 'MODULE_NOT_FOUND',
      requireStack: [
        'C:\\Users\\XXX\\ClientApp\\node_modules\\oxfmt\\dist\\embedded-DV4TApdj.js'
      ]
    }
  }
}

Node.js v24.11.0
```

**Comment by leaysgur** [comment]
@Boshen (Besides recommending pnpm,) do you have any other ideas?

I thought it was fixed after `npm@11.3` and wouldn't be reported anymore, but it seems still with `@11.6`.

**Comment by Boshen** [comment]
It's really hard to debug why your package manager is not installing the optional dependency, things you can try: https://oxc.rs/docs/guide/troubleshooting.html#cannot-find-native-binding-npm-has-a-bug-related-to-optional-dependencies

**Comment by DylanPiercey** [comment]
I believe the issue still exists and is related to https://github.com/npm/cli/issues/8628
