### ISSUE TITLE
VSCExtension: oxc client not found

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [oxc-project/oxc#8787]
![Image](https://github.com/user-attachments/assets/778fc5f0-0639-48cf-9d12-60b3e5da44f8)
```
ERR Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/<USER>/AppData/Roaming/Code/User/globalStorage/oxc.oxc-vscode': Error: Unable to resolve nonexistent file 'vscode-userdata:/c:/Users/<USER>/AppData/Roaming/Code/User/globalStorage/oxc.oxc-vscode'
```

This error occurs in 0.15.8

Also when trying to open the output panel

**Comment by Sysix** [comment]
I could not reproduce this error. 

Could you please try to reinstall the extension?

**Comment by sschneider-ihre-pvs** [comment]
Maybe it is a windows thing? I deleted all versions from  the .vscode folder and tried it. I am currently one version behind and that seems to work. So it might be introduced with the latest version.

**Comment by joshderochervlk-simplisafe** [comment]
I'm seeing this as well.
> Version: 1.96.4 (user setup)
Commit: cd4ee3b1c348a13bafd8f9ad8060705f6d4b9cba
Date: 2025-01-16T00:16:19.038Z
Electron: 32.2.6
ElectronBuildId: 10629634
Chromium: 128.0.6613.186
Node.js: 20.18.1
V8: 12.8.374.38-electron.0
OS: Windows_NT x64 10.0.22000

It's causing fixes on save not to work.

**Comment by Sysix** [comment]
Thanks you both. I created this bug by refactoring a bit too much. 
I created a PR to revert the changes. This should fix the problem

**Comment by joshderochervlk-simplisafe** [comment]
I uninstalled and reinstalled and it appears that I picked up the new version published at `2025-01-31, 16:43:54`, `0.15.8`. I am still seeing the same issue.

**Comment by Sysix** [comment]
>  picked up the new version published at 2025-01-31, 16:43:54, 0.15.8

https://marketplace.visualstudio.com/items?itemName=oxc.oxc-vscode

there  is no new version released and the update time does not match. 
Please wait for a new release which will be referenced in the PR.

**Comment by joshderochervlk-simplisafe** [comment]
> > picked up the new version published at 2025-01-31, 16:43:54, 0.15.8
> 
> https://marketplace.visualstudio.com/items?itemName=oxc.oxc-vscode
> 
> there is no new version released and the update time does not match. Please wait for a new release which will be referenced in the PR.

Ah, ok thanks. I'll check back. Thanks for the fix!
